### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by davidkaczer** [bauwenst/LaMoTO#1]
Add `wandb` and `scikit-learn` to `pyproject.toml`.

**Comment by bauwenst** [comment]
Thanks. `wandb` has been added in d2a2ab9.

`scikit-learn` is not used directly by LaMoTO, but since it is a dependency of `evaluate` and the HuggingFace maintainers [refuse to declare this](https://github.com/huggingface/evaluate/issues/394), I will add it into LaMoTO's dependencies in the next commit.
